# Generated by Django 3.1.2 on 2020-10-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('url', models.URLField()),
                ('xpath_country', models.CharField(max_length=1000)),
                ('regex_country', models.CharField(max_length=1000)),
                ('xpath_time', models.CharField(max_length=1000)),
                ('regex_time', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='country to monitor')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('html', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cram.page')),
            ],
        ),
    ]
